export const APP_CONSTANTS = {
    sampleRate: 48000,
    readChunkSize: 4096,
    searchQuerySyncDelayMs: 700,
    queryKeySearch: "search",
    queryKeyType: "type",
    queryKeyPlaying: "playing",
    storageKeyTweakbarHidden: "nyantracker:tweakbar-hidden",
    storageKeyVolume: "nyantracker:volume",
    storageKeySearch: "nyantracker:modland-search",
    storageKeySource: "nyantracker:browser-source",
    storageKeyBrowserWidth: "nyantracker:browser-width",
    storageKeyBrowserOpen: "nyantracker:browser-open",
    storageKeyOscHeight: "nyantracker:osc-height",
    minBrowserWidth: 280,
    minTrackerWidth: 520,
    minOscHeight: 200,
    patternMinHeight: 120,
    oscHideThreshold: 100,
} as const;
